:construction_worker: Pass git commit hash to docker build
inbo/alien-species-portal pull request #107
Opened 2024-07-19 11:50 UTC by TheJenne18

2024-07-19 12:08 UTC, SanderDevisscher requested changes
@TheJenne18 in the deployed version of the app the git sha is not displayed, see
![image](https://github.com/user-attachments/assets/667303b6-a164-4568-8844-769cbd5624b4)

2024-07-19 21:12 UTC, TheJenne18 commented
@SanderDevisscher bij deze is het opgelost:
<img width="973" alt="image" src="https://github.com/user-attachments/assets/f3347089-f223-4d72-aa13-5b80593c6f3b">

Nieuwe build gedaan hier: [https://github.com/inbo/alien-species-portal/actions/runs/10006175690/job/27658358008](https://github.com/inbo/alien-species-portal/actions/runs/10006175690/job/27658358008)

2024-07-22 08:33 UTC, SanderDevisscher approved these changes

2024-07-22 08:33 UTC, SanderDevisscher commented
@TheJenne18 thanks

2024-07-22 08:33 UTC, merged